Summary:
nosetests / system tests fail
Description:
CQL Driver version used: 1.0.8.
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
======================================================================
ERROR: system.test_thrift_server.TestMutations.test_bad_batch_calls
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 381, in setUp
    try_run(self.inst, ('setup', 'setUp'))
  File "/usr/local/lib/python2.7/site-packages/nose/util.py", line 478, in try_run
    return func()
  File "/var/lib/jenkins/jobs/Cassandra/workspace/test/system/__init__.py", line 113, in setUp
    self.define_schema()
  File "/var/lib/jenkins/jobs/Cassandra/workspace/test/system/__init__.py", line 158, in define_schema
    Cassandra.CfDef('Keyspace1', 'Super1', column_type='Super', subcomparator_type='LongType', row_cache_size=1000, key_cache_size=0),
TypeError: __init__() got an unexpected keyword argument 'key_cache_size'
Status:
RESOLVED
Priority:
Normal
Resolution:
Fixed
Affects_version:

Fix_version:
1.1.0
Component:
Legacy/Testing
Label:
None
Environment:

Attachment number:
0
Assignee:
Pavel Yaskevich
Reporter:
Michael Allen
Create date:
01/Feb/12 21:06
Update date:
16/Apr/19 09:32
Resolved date:
07/Feb/12 15:34
