Summary:
SizeEstimatesRecorder has assertions after decommission sometimes
Description:
Doing some testing with 2.1.8 adding and decommissioning nodes. Sometimes after decommissioning the following starts being thrown by the SizeEstimatesRecorder.
java.lang.AssertionError: -9223372036854775808 not found in -9223372036854775798, 10
at org.apache.cassandra.locator.TokenMetadata.getPredecessor(TokenMetadata.java:683) ~[cassandra-all-2.1.8.621.jar:2.1.8.621]
at org.apache.cassandra.locator.TokenMetadata.getPrimaryRangesFor(TokenMetadata.java:627) ~[cassandra-all-2.1.8.621.jar:2.1.8.621]
at org.apache.cassandra.db.SizeEstimatesRecorder.run(SizeEstimatesRecorder.java:68) ~[cassandra-all-2.1.8.621.jar:2.1.8.621]
at org.apache.cassandra.concurrent.DebuggableScheduledThreadPoolExecutor$UncomplainingRunnable.run(DebuggableScheduledThreadPoolExecutor.java:118) ~[cassandra-all-2.1.8.621.jar:2.1.8.621]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_40]
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_40]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_40]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_40]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_40]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_40]
at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
Status:
RESOLVED
Priority:
Normal
Resolution:
Fixed
Affects_version:

Fix_version:
2.1.12, 2.2.4, 3.0.0
Component:
Legacy/Coordination,
Label:
None
Environment:

Attachment number:
0
Assignee:
Paulo Motta
Reporter:
Jeremiah Jordan
Create date:
28/Jul/15 16:26
Update date:
16/Apr/19 09:31
Resolved date:
06/Nov/15 00:16
