Summary:
cqlsh connect error "member_descriptor' object is not callable"
Description:
When using cqlsh (Cassandra 2.1.0) with ssl, python 2.6.9. I get Connection error: ('Unable to connect to any servers',
{...: TypeError("'member_descriptor' object is not callable",)}
)
I am able to connect from another machine using python 2.7.5.
Status:
RESOLVED
Priority:
Low
Resolution:
Fixed
Affects_version:

Fix_version:
2.1.9, 2.2.0 rc2
Component:
Legacy/Tools
Label:
cqlsh lhf
Environment:

Attachment number:
0
Assignee:
Stefania
Reporter:
Digant Modha
Create date:
18/Sep/14 20:57
Update date:
16/Apr/19 09:31
Resolved date:
14/Jul/15 01:37
