Summary:
No exception thrown while during scanning no connection can be made to the regionserver
Description:
When a regionservers is stopped (shutdown or crash) and on the same moment a client performs a scan on that regionserver no exception is thrown at client side nor a reconnect toanother regionsserver is tried.
The ResultScanner.Iterator.hasNext ()just returns false, so the client assumes that there are no records anymore.
In the ScannerCallable.call I notice that the java.net.ConnectionException is catched and a empyt Result array is returned.
Status:
RESOLVED
Priority:
Major
Resolution:
Won't Fix
Affects_version:
0.20.1
Fix_version:
None
Component:
Client
Label:
None
Environment:

Attachment number:
0
Assignee:
Unassigned
Reporter:
Robert Hofstra
Create date:
11/Jan/10 15:52
Update date:
16/Jul/14 18:56
Resolved date:
16/Jul/14 18:56
